openapi: 3.0.3
info:
  title: Customer Management API
  version: 1.0.0
  description: API per la gestione dei clienti dell'hotel

paths:
  /customers:
    get:
      tags:
        - "customer"
      summary: Ottieni tutti i clienti
      operationId: getAllCustomers
      responses:
        '200':
          description: Lista dei clienti
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerDto'
    post:
      tags:
        - "customer"
      summary: Aggiungi un nuovo cliente
      operationId: addCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDto'
      responses:
        '201':
          description: Cliente creato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDto'

components:
  schemas:
    CustomerDto:
      type: object
      properties:
        id:
          type: integer
          example: 1
        firstName:
          type: string
          example: "Mario"
        lastName:
          type: string
          example: "Rossi"
        email:
          type: string
          format: email
          example: "mario.rossi@example.com"
        reservationIds:
          type: array
          items:
            type: integer
          example: [101, 102]
