openapi: 3.0.3
info:
  title: Hotel Booking API
  version: 1.0.0
  description: API per la gestione interna dell’hotel

paths:
  /rooms:
    get:
      summary: Ottieni tutte le stanze
      responses:
        '200':
          description: Lista di stanze
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomDto'
    post:
      summary: Aggiungi una nuova stanza
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomDto'
      responses:
        '201':
          description: Stanza creata con successo

  /rooms/available:
    get:
      summary: Ottieni le stanze disponibili
      responses:
        '200':
          description: Lista delle stanze disponibili
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomDto'

  /customers:
    get:
      summary: Ottieni tutti i clienti
      responses:
        '200':
          description: Lista dei clienti
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerDto'
    post:
      summary: Aggiungi un nuovo cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDto'
      responses:
        '201':
          description: Cliente creato con successo

  /reservations:
    get:
      summary: Ottieni tutte le prenotazioni
      responses:
        '200':
          description: Lista delle prenotazioni
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReservationDto'
    post:
      summary: Registra una nuova prenotazione
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationDto'
      responses:
        '201':
          description: Prenotazione registrata

  /reservations/{id}:
    delete:
      summary: Cancella una prenotazione
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Prenotazione cancellata

components:
  schemas:
    RoomDto:
      type: object
      properties:
        id:
          type: integer
        roomNumber:
          type: string
        type:
          $ref: '#/components/schemas/RoomType'
        availability:
          $ref: '#/components/schemas/Availability'

    CustomerDto:
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        reservationIds:
          type: array
          items:
            type: integer

    ReservationDto:
      type: object
      properties:
        id:
          type: integer
        customerId:
          type: integer
        roomId:
          type: integer
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date

    RoomType:
      type: string
      enum:
        - SINGLE
        - DOUBLE
        - SUITE

    Availability:
      type: string
      enum:
        - AVAILABLE
        - RESERVED
