openapi: 3.0.3
info:
  title: Hotel Booking API
  version: 1.0.0
  description: API per la gestione interna dell’hotel

paths:
  /rooms:
    get:
      summary: Ottieni tutte le stanze
      operationId: getRooms
      responses:
        '200':
          description: Lista di stanze
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomDto'
    post:
      summary: Aggiungi una nuova stanza
      operationId: addRoom
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomDto'
      responses:
        '201':
          description: Stanza creata con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomDto'

  /rooms/available:
    get:
      summary: Ottieni le stanze disponibili
      operationId: getAvailableRooms
      description: metodo che ritorna la stanza se la disponibilità è TRUE
      responses:
        '200':
          description: Lista delle stanze disponibili
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomDto'

  /customers:
    get:
      summary: Ottieni tutti i clienti
      operationId: getAllCustomers
      responses:
        '200':
          description: Lista dei clienti
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerDto'
    post:
      summary: Aggiungi un nuovo cliente
      operationId: addCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerDto'
      responses:
        '201':
          description: Cliente creato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerDto'

  /reservations:
    get:
      summary: Ottieni tutte le prenotazioni
      operationId: getAllReservations
      responses:
        '200':
          description: Lista delle prenotazioni
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReservationDto'
    post:
      summary: Registra una nuova prenotazione
      operationId: addReservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationDto'
      responses:
        '201':
          description: Prenotazione registrata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationDto'

  /reservations/{id}:
    delete:
      summary: Cancella una prenotazione
      operationId: deleteReservation
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Prenotazione cancellata


components:
  schemas:
    RoomDto:
      type: object
      properties:
        id:
          type: integer
        roomNumber:
          type: string
        available:
          type: boolean
        type:
          $ref: '#/components/schemas/RoomType'


    CustomerDto:
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        reservationIds:
          type: array
          items:
            type: integer

    ReservationDto:
      type: object
      properties:
        id:
          type: integer
        customerId:
          type: integer
        roomId:
          type: integer
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date


    RoomType:
      type: string
      enum:
        - SINGLE
        - DOUBLE
        - SUITE