openapi: 3.0.3
info:
  title: Hotel Booking API
  version: 1.0.0
  description: API per la gestione interna dell’hotel

paths:
  /reservations:
    get:
      tags:
        - "Reservation"
      summary: Ottieni tutte le prenotazioni
      operationId: getAllReservations
      responses:
        '200':
          description: Lista delle prenotazioni
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReservationDto'
    post:
      tags:
        - "Reservation"
      summary: Registra una nuova prenotazione
      operationId: addReservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationDto'
      responses:
        '201':
          description: Prenotazione registrata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationDto'

  /reservations/{id}:
    delete:
      tags:
        - "Reservation"
      summary: Cancella una prenotazione
      operationId: deleteReservation
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Prenotazione cancellata

components:
  schemas:
    ReservationDto:
      type: object
      properties:
        id:
          type: integer
        customerId:
          type: integer
        roomId:
          type: integer
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
