openapi: 3.0.3
info:
  title: Room Management API
  version: 1.0.0
  description: API per la gestione delle stanze dell'hotel

paths:
  /rooms:
    get:
      tags:
        - "rooms"
      summary: Ottieni tutte le stanze
      operationId: getRooms
      responses:
        '200':
          description: Lista di stanze
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomDto'
    post:
      tags:
        - "rooms"
      summary: Aggiungi una nuova stanza
      operationId: addRoom
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomDto'
      responses:
        '201':
          description: Stanza creata con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomDto'

  /rooms/available:
    get:
      tags:
        - "rooms"
      summary: Ottieni le stanze disponibili
      operationId: getAvailableRooms
      description: Ritorna la lista delle stanze con disponibilità impostata a TRUE
      responses:
        '200':
          description: Lista delle stanze disponibili
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomDto'

components:
  schemas:
    RoomDto:
      type: object
      properties:
        id:
          type: integer
          example: 1
        roomNumber:
          type: string
          example: "101A"
        available:
          type: boolean
          example: true
        roomType:
          type: string
          enum:
            - SINGLE
            - DOUBLE
            - SUITE


